### ISSUE TITLE
[Survey] Set up Survey Monkey

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#14]
@tamigraph do you think Survey Monkey could be the right tool for us? Let me know if you have other options on your mind.

**Comment by holanita** [comment]
Just to keep in mind, we need a tool that offers ranking questions. SM does for sure:
https://help.surveymonkey.com/en/create/ranking-question/

**Comment by holanita** [comment]
Chris: figure out accessibility @mrchrisadams please add details

**Comment by holanita** [comment]
@seanmcilroy29 can you please help us set up an account for Survey Monkey

**Comment by holanita** [comment]
Last week Sean signed up for SM and I added the [draft survey](https://www.surveymonkey.com/r/Preview/?sm=0VKpgfUwJtdFhr1nqqhXmmGA6aKcxGyjyjYsY3LoeHVCE0kVd6hw08FPTbZbjm8_2F) already.

Based on the last update I received from Asim, we might switch to https://yougov.co.uk/ instead of Survey Monkey. Ismael suggested this new tool at the end of last week. This is to be discussed asap as setting up a new and unknown tool might require quite some time and could delay the process. 

@jawache and @Leamsi9 I'm reaching out to you guys via Slack as well to speed things up.

**Comment by jawache** [comment]
@Leamsi9 I believe if I can summarise the meeting properly. 

Apparently YouGov and SurveyMonkey BOTH have some form of paid feature where you can pay them for people to fill out your survey. Am i correct?

@Leamsi9 I believe you said that there were some differences between the two paid for offerings and you preferred the offerings from YouGov, maybe you can target people better? I'm not sure.

Given the momentum already towards SurveyMonkey I think the benefits from YouGov have to be strong to flip away from SurveyMonkey (as in, if YouGov solves all the headaches we'll have from Nov/Dec regarding trying toget people to fill out the survey then that would be worthwhile stopping and re-tooling to YouGov otherwise we should go ahead with SurveyMonkey) I don't have enough experience/visibility to make that call. 

If we can't make the call end of today let's move forward with Survey Money so @holanita is unblocked.

**Comment by holanita** [comment]
@jawache thanks @Leamsi9 what do you think?

Just one note: to me it sounds like yougov surveys can only be completed by their own people. So if that means we have to ask our people and any software practitioner out there to sign up for yougov, then that's a no go I guess. It could still be a nice add-on to compliment survey monkey, but not to replace it.

**Comment by holanita** [comment]
I'm moving forward with Survey Monkey. In any case, will ask Sean to investigate what panel they (SM) offer and how much it would cost to use them.

**Comment by holanita** [comment]
Waiting for a few questions to be confirmed, but the survey is still available at the [link](https://www.surveymonkey.com/r/Preview/?sm=0VKpgfUwJtdFhr1nqqhXmmGA6aKcxGyjyjYsY3LoeHVCE0kVd6hw08FPTbZbjm8_2F) I shared last Friday.

**Comment by holanita** [comment]
All sorted, the survey is still available for review [here](https://www.surveymonkey.com/r/Preview/?sm=0VKpgfUwJtdFhr1nqqhXmmGA6aKcxGyjyjYsY3LoeHVCE0kVd6hw08FPTbZbjm8_2F).

**Comment by holanita** [comment]
Discussed in today's WG call. Team to review and comment with 24 hours.

**Comment by holanita** [comment]
No feedback received, so I'm closing this.
