### ISSUE TITLE
Create SoGS post-launch marketing plan

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/state-of-green-software#21]
**Why**: From Nov 10th to Dec 31st we need as many people as possible to complete our state of green software survey.
**What**:  The State of Green Software is a report we are creating for Q1 2023, part of it will come from the results of an online survey of developers. Post COP we have 6 weeks to get as many people as possible to fill out that survey.

Scope:
- We want 5000 developers to fill out this survey in 6 weeks.
- The survey takes about 11 mins to fill out.
- They will need to visit stateof.greensoftware.org to see some details and fill out the report.
- We want to reach out to our own social networks, our own email lists, other partners.
- We might want to do another paid campaign later on in the 6 weeks to target demographics that are not filling out the survey.
- We want our member orgs to share these surveys internally with their employees.
- We need a detailed marketing plan for how we are going to make the above happen by the COP launch date so immediately after launch we have clarity regarding what everyone is doing to achieve the above.

@Leamsi9 and @NAMRATA-WOKE should work on this together - proposed format https://docs.google.com/document/d/1NFXnUhXZj5g__WHW3hzLXslmo1WX93lu0Fey-9zqXLA/edit#heading=h.jey55uwbk4yo

**Comment by Leamsi9** [comment]
Here as promised is braindump 1.0. It focuses exclusively on the survey, not the wider SoGS report.

**Target**
5000 replies ambitious. Average survey responses tend to be around 15-20% so we would need to reach 25000-35,000 devs with our survey. 1000 still seems high but more achievable.  


**Suggested lines of action**


1. Mobilise big GSF members to distribute survey across all software engineering teams in their organisation. Intel, Microsoft, Accenture,  etc. This may or may not require @jawache "breaking the glass". Offer disaggregated organisation specific insights in exchange for organisation wide distribution.


2. *Really* harness Linux Foundation. Pretty much every single person in its database is in our target audience. How far can we really push their channels? Again, if this is a priority, might be glass breaking one off by @jawache for massive reach.


3. Promote the survey directly with a good incentive. For very large distributions, 3-5 biggish prices can be good incentives. Means you don't give everyone something but you make it worth a punt.

One of the most direct ways to reach a targeted, non-green-already dev specific audience for free and at scale would be to at least temporarily subscribe to lots of dev slack channels, and post there.  The rhythm and copy would need to be thought about so it doesn't come across as spam.


3.1 consider advertising on Reddit.


3.2  reach out to regional and national tech hubs and networks (African, Latin American, SE Asia,  etc) for greater diversity.


3.3 Push on dev twitter every day with valuable content. Maybe do a one month hashtag campaign #greenyoursoftware where every day we share a green pattern and a survey link? This could also run on other channels.


3.4  Consider partnering or piggybacking on forthcoming conferences. Could Gael promote/distribute the survey at API Days Paris since youre speaking at it Asim? Any other dev conferences who might distribute?



4. Consider using an existing commercial survey panel. Survey monkey has one, not sure if developer specific. Yougov definitely will have a dev-specific panel and price would be c.$1 per survey answer. If we really want numbers, yougov would be better. YouGov might also make the survey more credible. This could guarantee say 500 or even 1000 responses (maybe), so you know you have something to show no matter what.

Over to @jawache and @NAMRATA-WOKE to approve/comment.

**Comment by jawache** [comment]
Let's break this out to 

- Paid Solutions
Who, when, how much.
- Organic / Social Media
Need a calendar of posts.
- Partnerships
Which organizations can we partner with, same as for the hackathon.
Who is going to reach out to them.
- Members & LF
What's the strategy for getting these people onboard and spreading the survey.
Do I need to setup individual meetings with member orgs over November/December?
What am I going to share with them? (This is where designs or a much more fully fleshed out repot would help?)

**Comment by zanete** [comment]
Moved the above comments to a [google doc](https://docs.google.com/document/d/1NFXnUhXZj5g__WHW3hzLXslmo1WX93lu0Fey-9zqXLA/edit#heading=h.jey55uwbk4yo) for better collaboration

**Comment by Leamsi9** [comment]
@jawache and @holanita I've rejigged all my suggestions above and incorporated the market research Anita and I did into survey panels into the Google Doc @zanete created. It now follows all your headings @jawache .

**Comment by jawache** [comment]
@holanita & @Leamsi9 - the above doc is a good start but let me define some more concrete aspects of this deliverable.

**By 10th November** I would like
- [ ] A calendar at least 2 weeks out for exactly what will happen **every day** post launch. I would like there to be no confusion regarding who is expected to do what and when. Post launch we should be able to execute without need for daily meetings and frantic communications.
- [ ] What are our marketing KPIs and what exactly do we need to do to measure those KPIs?
- [ ] A strategy for figuring out the ROI on different marketing activities, right now we just do everything in the hope that one thing works, after this exercise I'd like to get a better understanding of which of the channels we employ get's us the most impact so we can focus on those activities in the future.
- [ ] Weekly targets so we know if we are on-track or off and a decision now for when to pull the emergency cord (paid for marketing for instance)

**Comment by holanita** [comment]
Noted. TBD in today's call if and how we should involve Namrata OR start from scratch.

**Comment by holanita** [comment]
Note from today's call. Ismael could not attend, so we'll try to schedule another one with him for Monday morning.
- Asim to schedule 1-on-1 calls with org leads where he can also pitch the survey
- We should prepare a package for orgs to pitch
- We should give each org a dedicated survey monkey link so their responses can be separated from the rest

**Comment by zanete** [comment]
@holanita do you think it's worth adding the asks from @jawache [comment](https://github.com/Green-Software-Foundation/state-of-green-software/issues/21#issuecomment-1295057677) as headings in the google doc to keep it all in one place and make use of the gdoc commenting feature for specific feedback? Happy to arrange if you're ok with that or would you prefer to do it yourself?

**Comment by holanita** [comment]
@zanete we had not time for this in today's call. I'd rather wait, but feel free to go ahead if you prefer

**Comment by holanita** [comment]
I've added a short summary [to the google doc](https://docs.google.com/document/d/1NFXnUhXZj5g__WHW3hzLXslmo1WX93lu0Fey-9zqXLA/edit#) as Zanete suggested but wanted to add here as well for transparency @jawache @NAMRATA-WOKE 

By 10th November:
- 2-week calendar detailing daily activities incl. owners, tasks, exact timings **(need Namrata's help & expertise)**
- Marketing KPIs and how to measure them **(TBD in our call with Ismael & Asim on Nov 2)**
- Figuring out the ROI on different marketing activities **(I don't know anything about this. Can Namrata help?)**
- Weekly targets to track so we know when to pull the emergency cord **(easy, just need to know the tasks/activities)**

**Comment by holanita** [comment]
@NAMRATA-WOKE hi. can you help me with this? lmk if it's easier to hop on a call. it would be helpful to know:
- what marketing actions should we incorporate (what type, what frequency, will each task be completed by you?, etc)
- do you have a well defined process for these plans? maybe a GH board that I should copy to match your current workflow?

**Comment by NAMRATA-WOKE** [comment]
@holanita Yes - a phone call is a good idea! Anytime after the 2nd.  Doing a small brain dump here to help you prepare for our conversation:

There is a lot about SoGS I don't know so before I make any recommendations, it will be helpful to know more about how this report is being put together, the timeline, the actors involved (internally and externally), and existing plans for production and release (e.g., are the contents of this report all coming out at one time? Is this purely a digital report or will this also go to print for certain stakeholders/members?) 

Regarding ROI - a couple of considerations/elements should factor into setting realistic targets:

**1. Size of industry/ niche field**

**2. Desired impact (this could be related to many things):**
- The # of survey respondents 
- Existing network size + the number of new members/stakeholders required to meet future organizational objectives 
- How many people are talking about SoGS (this is typically an engagement %) - having a designated hashtag can be helpful in identifying and consolidating this information (i.e., #SOGS2022)
- Impressions (the number of people who have seen SoGS communication - even if they didn't click, comment, or otherwise engage with that communication) - contrary to popular opinion, this is an important metric for field builders like GSF because it helps give some marker to the reachability of your communication and content, and the stretch power of your existing network/ what your existing network is willing to do for the Foundation 
- Media features -- ties into the efforts made to acquire earned media coverage (use a # versus % for this one)
- Media mentions -- # of times SOGS2022 is mentioned in the news, and in blogs, podcasts, interviews, panel discussions 

**3. Resourcing (e.g., staffing, time, capital)** 

So for ROI, you can't have one number. You need to break down ROI into several metrics for evaluation to get a real understanding of where your marketing and communication efforts did well, and where they fell short. Doing so will also make it a lot less nerve-wracking when you do decide to veer off course or pivot in your approach, because you'll quickly be able to access how that change will affect all other activities. 

I also recommend having a couple of tiers of ROI (immediate (initial 30 days), short-term (3 months) and long-term(+6 months).

**Comment by holanita** [comment]
@NAMRATA-WOKE 
- see [here](https://docs.google.com/document/d/1NFXnUhXZj5g__WHW3hzLXslmo1WX93lu0Fey-9zqXLA/edit#bookmark=id.phvchr31werb) the answers to your questions about the report
- the questions you had about ROI are to be discussed with Asim 
- and I think the generic Qs will be useful for all of our marketing activities, not just SOGS (size of industry and network, etc.)
- my evenings are really busy this week. are you free around 6.30 or 7pm GMT tomorrow?

**Comment by holanita** [comment]
@jawache @NAMRATA-WOKE I've been thinking about ways to have the best results with the least effort.

My idea would be to **offer a benchmark report for organizations** if a certain number of their employees complete the survey. We would compare the company's results with overall industry results. I mentioned this before, but now I thought about the whole plan.

The ask & the offer:
- a basic report for those who have **at least 10,000 (?) respondents**
- an advanced report for those who have **at least 50,000 (?) respondents**

The effort: 
- the **basic report** could be something like [this dashboard](https://www.surveymonkey.com/stories/SM-uAIjWO4BexCEGzykxJqoWg_3D_3D) but with better **graphs** and GSF design (just need a template that we can populate with data exported from Survey Monkey)
- in the **advanced report** we could add an **executive summary** with key findings and a **swot analysis** too (we could use a template for this, but we also need someone to do the analysis)

ROI: 
This will be easy to track based on response rates in Survey Monkey. If this was interesting to our member organisations and at least 10 of them would sign up, we could generate at least 500,000 responses relatively easily imo.
Also, this plan seems to be easy to scale (by engaging more or more big organisations) so I can imagine we could end up with a huge coverage on the long run.

I've added some more details [in this doc](https://docs.google.com/document/d/1xi9T2NuKsZ4SHq3p_OyFFVZ2ACm1zD9H21jwuGsI8xY/edit#heading=h.33mb9e2rj1u4). We can do a whole lot of other things as well of course, but having a solid basis that would give us a nice pool of respondents could alleviate the pressure...

What do you think?

**Comment by NAMRATA-WOKE** [comment]
@holanita I am free to speak today between 2-3pm ET today.

**Comment by holanita** [comment]
@NAMRATA-WOKE I'll reach out in a DM. Meanwhile, we had a call with Tamara & Zane. Numbers have been updated above.

**Comment by holanita** [comment]
To be discussed in a call with Asim this week. As he suggested today, benchmark reports will be offered to **members only**!

**Comment by holanita** [comment]
I'm closing this ticket as we already have a marketing plan.
- Next steps have been added to github. Each issue is labeled as 'marketing'. See them all [here](https://github.com/Green-Software-Foundation/state-of-green-software/issues?q=is%3Aissue+is%3Aopen+label%3Amarketing) or [in this marketing board](https://github.com/orgs/Green-Software-Foundation/projects/3/views/4).
- https://github.com/Green-Software-Foundation/state-of-green-software/issues/46 – I will be using this ticket to manage the first week.
- https://github.com/Green-Software-Foundation/state-of-green-software/issues/41 – this list will be updated on an ongoing basis
