### ISSUE TITLE
Desk research for culture

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/state-of-green-software#50]
What: finalize the desk research for the culture section
Who: Ismael
When: Nov 25

**Comment by holanita** [comment]
Might be delayed as [this first one](https://github.com/Green-Software-Foundation/state-of-green-software/issues/48) is delayed too.

**Comment by Leamsi9** [comment]
Desktop research 25% complete (focused on regulations and standards). On track for deadline.

**Comment by holanita** [comment]
Just adding a note here that this is 3 days behind schedule.

**Comment by holanita** [comment]
Delayed due to the delay with the business case and culture.

**Comment by holanita** [comment]
ETA _hopefully today_ as per Ismael.

**Comment by holanita** [comment]
@Leamsi9 haven't heard from you this week, hope all is well? Let us know when you have any updates pls.

**Comment by Leamsi9** [comment]
Apologies, as I explained I had connectivity issues after landing in Mexico. Culture draft is in.

**Comment by holanita** [comment]
@jawache please review

**Comment by jawache** [comment]
Hia, I need to understand what we mean by a "draft"

We have a definition that a draft is a section that is complete and ready for review and processing to the next stage.

@Leamsi9 help me understand whats going on, how can we be at that stage without incorporating the survey and interviews? I'm incredibly confused.

**Comment by holanita** [comment]
@jawache this is supposed to be the draft desk research. Interviews and survey findings will be incorporated in January, that's when Ismael will be working on drafting the actual report.

**Comment by holanita** [comment]
Received in Slack over the weekend:
Asim Here is the Culture section reworked as Insight cards and elaborations. I'm hoping I've captured your vision. In revisiting it I couldn't resist strengthening it, so the business section is significantly improved and I still want to make a few desk research additions, but I thought I'd release today as promised so you can let me know if I've done what you hoped, and release Tooling and Knowledge in the same kind of format.
If you approve this desk research website draft, I will replace the existing section 5 with this new version.
https://docs.google.com/document/d/1vVlxQvASWr_a4P8vJxM5mATLYIiRCdzuN0y1GUvN3Aw/edit#

**Comment by jawache** [comment]
@Leamsi9 and @holanita I've made some comments to clarify that an Insight is what will appear on a Card on the homepage of the report (it's got subheadings called Card as well which originally confused me). As long as we are clear that each insight is what will appear on a card then this is inline with expectations for the design of the final report, so it feels good to me.

If we carry on like this we'll be well prepped for making the website, in Jan Osama can almost just take this content as is and will be able to start makeing the website.

@Leamsi9 you've left the titles as Insight 1, 2, 3, 4 etc... which is fine, I think it's better to come up with the summary titles closer to the end as they might change as other data is added.

@holanita I made a suggestion that might be good to get Namrata's opinion on what to name the insights as we get closer to naming them. Esp. considering we want to design the wording for an insight so it's impactful, viral, sharable - she might have some good ideas for how to name an insight for max marketing reach.

Cheers!

**Comment by Leamsi9** [comment]
That's great. Glad it works, I did aim to rewrite it in such a way that it could just be cut and pasted into the website with some pretty design work to beautify it. Specially the tables and graphs might benefit from being replicated in our house style.


And yes the Card  sections refers to the Insight cards on the Figma template, and the Treatment refers to the content on the template when you click through on the figma card.

I didn't title the insights because I didn't notice titles on the Figma version, just a group of cards with tags. I also think we could benefit from more thought on tagging, in case we want to drill down, for instance, into the TOC like I did in my original report draft. So one Insight could be tagged, `Tech Culture` and `market pressures` for example (although I prefer "drivers" personally). But we can presumably add tags once the whole is up.

Happy for @NAMRATA-WOKE to name the Insight titles. 

With this and your doc comments I will proceed accordingly with Knowledge, Tooling and Business Plan.

@jawache Do you want them all in a single new doc, all in the old doc replacing what's there now in the old report format, or as individual documents as per this example, in a sogs website folder, so each doc can be added to the website as they come out?

**Comment by Leamsi9** [comment]
@jawache I've replied to your comments in the doc and revised it as per your comments. Could do with confirmation that I now have your vision down in the structure. Also proposed an indicators approach, see if you like it. Shouldn't add much work.

**Comment by Leamsi9** [comment]
@jawache in the end I decided to work on further strengthening the Culture doc. When you have a moment, please check that it fits your vision in terms of format? I tried to integrate your comments, and turned the references into hyperlinks. Will be adding more references later. 

I think it now makes the business case much more strongly, covering market size and trends, green public procurement and also green software procurement by business, and more comprehensive regulatory and standards content with a more developed USA dimension and mention of China, etc. It's always a case of how long is a piece of string, but I feel I can draw a line on the desk research here now and feel it covers the bases.

**Comment by holanita** [comment]
Closing these individual tasks and will summarize all the essential details and next steps in one document. 

Culture:
- [Insights](https://docs.google.com/document/d/1vVlxQvASWr_a4P8vJxM5mATLYIiRCdzuN0y1GUvN3Aw/edit#) 
- we could benefit from more thought on tagging
- get Namrata's opinion on what to name the insights as we get closer to naming them (should be impactful, viral, sharable)
